/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.burgermenuapp;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;





public class BurgerMenuApp extends javax.swing.JFrame {

    private JSpinner spinnerKetchup;
    private JSpinner spinnerBarbacoa;
    private JSpinner spinnerMostaza;
    private JSpinner spinnerThai;

    /**
     * Creates new form BurgerMenuApp
     */
    public BurgerMenuApp() {
        initComponents();
       
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_CarneHamburguesa = new javax.swing.ButtonGroup();
        btnGroup_Pan = new javax.swing.ButtonGroup();
        btnGroup_Patatas = new javax.swing.ButtonGroup();
        btnGroup_Bebida = new javax.swing.ButtonGroup();
        btnGroup_Entrega = new javax.swing.ButtonGroup();
        jPanel1 = new ImagePanel("./burger-photo.jpg");
        textField_PrecioFinal = new javax.swing.JTextField();
        label_PrecioFinal = new javax.swing.JLabel();
        textField_IVA = new javax.swing.JTextField();
        label_IVA = new javax.swing.JLabel();
        label_RecogidaLocal = new javax.swing.JLabel();
        label_Precio = new javax.swing.JLabel();
        textField_Precio = new javax.swing.JTextField();
        label_Pedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_Pedido = new javax.swing.JTextArea();
        btn_ConfirmarPedido = new javax.swing.JButton();
        menuBar_BurgerApp = new javax.swing.JMenuBar();
        menu01 = new javax.swing.JMenu();
        menuHamburguesa = new javax.swing.JMenu();
        menuItem_HamburguesaPollo = new MyCheckMenuItem();
        menuItem_HamburguesaCerdo = new MyCheckMenuItem();
        menuItem_HamburguesaTernera = new MyCheckMenuItem();
        menuItem_HamburguesaVegana = new MyCheckMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuPan = new javax.swing.JMenu();
        menuItem_PanNormal = new MyCheckMenuItem();
        menuItem_PanIntegral = new MyCheckMenuItem();
        menuItem_PanCenteno = new MyCheckMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuPatatas = new javax.swing.JMenu();
        menuItem_PatatasFritas = new MyCheckMenuItem();
        menuItem_PatatasGajo = new MyCheckMenuItem();
        menuItem_PatatasCaseras = new MyCheckMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuBebida = new javax.swing.JMenu();
        menuItem_BebidaCola = new MyCheckMenuItem();
        menuItem_BebidaNaranja = new MyCheckMenuItem();
        menuItem_BebidaLimon = new MyCheckMenuItem();
        menuItem_BebidaAgua = new MyCheckMenuItem();
        menuItem_BebidaCerveza = new MyCheckMenuItem();
        menu02 = new javax.swing.JMenu();
        menuExtra_HamburguesaDoble = new MyCheckMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuExtra_Queso = new MyCheckMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuExtra_Patatas = new MyCheckMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        spinnerKetchup=new javax.swing.JSpinner();
        spinnerKetchup.setModel(new SpinnerNumberModel(0,0,10,1));
        spinnerBarbacoa=new javax.swing.JSpinner();
        spinnerBarbacoa.setModel(new SpinnerNumberModel(0,0,10,1));
        spinnerMostaza=new javax.swing.JSpinner();
        spinnerMostaza.setModel(new SpinnerNumberModel(0,0,10,1));
        spinnerThai=new javax.swing.JSpinner();
        spinnerThai.setModel(new SpinnerNumberModel(0,0,10,1));
        menuSalsas = new javax.swing.JMenu();
        menuItem_SalsasKetchup = new MyCheckMenuItem();
        menuItem_SalsasBarbacoa = new MyCheckMenuItem();
        menuItem_SalsasMostaza = new MyCheckMenuItem();
        menuItem_SalsasThai = new MyCheckMenuItem();
        menu03 = new javax.swing.JMenu();
        menuItem_Domicilio = new MyCheckMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuItem_Local = new MyCheckMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        textField_PrecioFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_PrecioFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_PrecioFinal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        label_PrecioFinal.setForeground(new java.awt.Color(253, 253, 233));
        label_PrecioFinal.setText("Precio Final: ");

        textField_IVA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_IVA.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_IVA.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        label_IVA.setForeground(new java.awt.Color(253, 253, 233));
        label_IVA.setText("Precio con IVA (21%):");

        label_RecogidaLocal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        label_RecogidaLocal.setForeground(new java.awt.Color(253, 253, 233));
        label_RecogidaLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        label_Precio.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        label_Precio.setForeground(new java.awt.Color(253, 253, 233));
        label_Precio.setText("Precio:");

        textField_Precio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_Precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        label_Pedido.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        label_Pedido.setForeground(new java.awt.Color(253, 253, 233));
        label_Pedido.setText("Pedido:");

        textArea_Pedido.setColumns(20);
        textArea_Pedido.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        textArea_Pedido.setRows(5);
        jScrollPane1.setViewportView(textArea_Pedido);

        btn_ConfirmarPedido.setBackground(new java.awt.Color(228, 52, 52));
        btn_ConfirmarPedido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ConfirmarPedido.setText("Confirmar Pedido");
        btn_ConfirmarPedido.setBorder(null);
        btn_ConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(label_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_PrecioFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textField_PrecioFinal)
                            .addComponent(textField_IVA)
                            .addComponent(textField_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addComponent(label_RecogidaLocal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(177, 177, 177))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ConfirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_ConfirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textField_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textField_IVA, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(label_IVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(label_RecogidaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_PrecioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        menuBar_BurgerApp.setBackground(new java.awt.Color(240, 61, 102));
        menuBar_BurgerApp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar_BurgerApp.setFocusable(false);
        menuBar_BurgerApp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        menuBar_BurgerApp.setPreferredSize(new java.awt.Dimension(187, 48));

        menu01.setText("Menú");
        menu01.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        menuHamburguesa.setText("Carne Hamburguesa");
        menuHamburguesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuHamburguesa.setMargin(new java.awt.Insets(6, 2, 6, 2));

        btnGroup_CarneHamburguesa.add(menuItem_HamburguesaPollo);
        menuItem_HamburguesaPollo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_HamburguesaPollo.setSelected(true);
        menuItem_HamburguesaPollo.setText("Pollo");
        menuItem_HamburguesaPollo.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuItem_HamburguesaPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_HamburguesaPolloActionPerformed(evt);
            }
        });
        menuHamburguesa.add(menuItem_HamburguesaPollo);

        btnGroup_CarneHamburguesa.add(menuItem_HamburguesaCerdo);
        menuItem_HamburguesaCerdo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_HamburguesaCerdo.setText("Cerdo");
        menuItem_HamburguesaCerdo.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuHamburguesa.add(menuItem_HamburguesaCerdo);

        btnGroup_CarneHamburguesa.add(menuItem_HamburguesaTernera);
        menuItem_HamburguesaTernera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_HamburguesaTernera.setText("Ternera (+1€)");
        menuItem_HamburguesaTernera.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuHamburguesa.add(menuItem_HamburguesaTernera);

        btnGroup_CarneHamburguesa.add(menuItem_HamburguesaVegana);
        menuItem_HamburguesaVegana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_HamburguesaVegana.setText("Vegana (+1€)");
        menuItem_HamburguesaVegana.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuHamburguesa.add(menuItem_HamburguesaVegana);

        menu01.add(menuHamburguesa);
        menu01.add(jSeparator1);

        menuPan.setText("Tipo de Pan");
        menuPan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPan.setMargin(new java.awt.Insets(6, 2, 6, 2));

        btnGroup_Pan.add(menuItem_PanNormal);
        menuItem_PanNormal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_PanNormal.setSelected(true);
        menuItem_PanNormal.setText("Normal");
        menuItem_PanNormal.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuPan.add(menuItem_PanNormal);

        btnGroup_Pan.add(menuItem_PanIntegral);
        menuItem_PanIntegral.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_PanIntegral.setText("Integral");
        menuItem_PanIntegral.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuPan.add(menuItem_PanIntegral);

        btnGroup_Pan.add(menuItem_PanCenteno);
        menuItem_PanCenteno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_PanCenteno.setText("Centeno");
        menuItem_PanCenteno.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuPan.add(menuItem_PanCenteno);

        menu01.add(menuPan);
        menu01.add(jSeparator2);

        menuPatatas.setText("Tipo de Patatas");
        menuPatatas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPatatas.setMargin(new java.awt.Insets(6, 2, 6, 2));

        btnGroup_Patatas.add(menuItem_PatatasFritas);
        menuItem_PatatasFritas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_PatatasFritas.setSelected(true);
        menuItem_PatatasFritas.setText("Fritas");
        menuItem_PatatasFritas.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuPatatas.add(menuItem_PatatasFritas);

        btnGroup_Patatas.add(menuItem_PatatasGajo);
        menuItem_PatatasGajo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_PatatasGajo.setText("Gajo");
        menuItem_PatatasGajo.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuPatatas.add(menuItem_PatatasGajo);

        btnGroup_Patatas.add(menuItem_PatatasCaseras);
        menuItem_PatatasCaseras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_PatatasCaseras.setText("Caseras (+1€)");
        menuItem_PatatasCaseras.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuPatatas.add(menuItem_PatatasCaseras);

        menu01.add(menuPatatas);
        menu01.add(jSeparator3);

        menuBebida.setText("Bebida");
        menuBebida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuBebida.setMargin(new java.awt.Insets(6, 2, 6, 2));

        btnGroup_Bebida.add(menuItem_BebidaCola);
        menuItem_BebidaCola.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_BebidaCola.setSelected(true);
        menuItem_BebidaCola.setText("Coca Cola");
        menuItem_BebidaCola.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuBebida.add(menuItem_BebidaCola);

        btnGroup_Bebida.add(menuItem_BebidaNaranja);
        menuItem_BebidaNaranja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_BebidaNaranja.setText("Fanta de Naranja");
        menuItem_BebidaNaranja.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuBebida.add(menuItem_BebidaNaranja);

        btnGroup_Bebida.add(menuItem_BebidaLimon);
        menuItem_BebidaLimon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_BebidaLimon.setText("Fanta de Limón");
        menuItem_BebidaLimon.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuItem_BebidaLimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_BebidaLimonActionPerformed(evt);
            }
        });
        menuBebida.add(menuItem_BebidaLimon);

        btnGroup_Bebida.add(menuItem_BebidaAgua);
        menuItem_BebidaAgua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_BebidaAgua.setText("Agua");
        menuItem_BebidaAgua.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuBebida.add(menuItem_BebidaAgua);

        btnGroup_Bebida.add(menuItem_BebidaCerveza);
        menuItem_BebidaCerveza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_BebidaCerveza.setText("Cerveza");
        menuItem_BebidaCerveza.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuBebida.add(menuItem_BebidaCerveza);

        menu01.add(menuBebida);

        menuBar_BurgerApp.add(menu01);

        menu02.setText("Extras");
        menu02.setFocusable(false);
        menu02.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        menuExtra_HamburguesaDoble.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuExtra_HamburguesaDoble.setText("Hamburguesa doble (+2 €)");
        menuExtra_HamburguesaDoble.setMargin(new java.awt.Insets(6, 2, 6, 2));
        menuExtra_HamburguesaDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExtra_HamburguesaDobleActionPerformed(evt);
            }
        });
        menu02.add(menuExtra_HamburguesaDoble);
        menu02.add(jSeparator5);

        menuExtra_Queso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuExtra_Queso.setText("Extra de queso (+0,50 €)");
        menuExtra_Queso.setMargin(new java.awt.Insets(6, 2, 6, 2));
        menu02.add(menuExtra_Queso);
        menu02.add(jSeparator6);

        menuExtra_Patatas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuExtra_Patatas.setText("Extra de patatas (+1 €)");
        menuExtra_Patatas.setMargin(new java.awt.Insets(6, 2, 6, 2));
        menu02.add(menuExtra_Patatas);
        menu02.add(jSeparator7);

        menuSalsas.setText("Salsas");
        menuSalsas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuSalsas.setMargin(new java.awt.Insets(6, 2, 6, 2));

        menuItem_SalsasKetchup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_SalsasKetchup.setText("Ketchup (+0,50 €)");
        menuItem_SalsasKetchup.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuSalsas.add(menuItem_SalsasKetchup);
        menuSalsas.add(spinnerKetchup);

        menuItem_SalsasBarbacoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_SalsasBarbacoa.setText("Barbacoa (+0,50 €)");
        menuItem_SalsasBarbacoa.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuItem_SalsasBarbacoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_SalsasBarbacoaActionPerformed(evt);
            }
        });
        menuSalsas.add(menuItem_SalsasBarbacoa);
        menuSalsas.add(spinnerBarbacoa);

        menuItem_SalsasMostaza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_SalsasMostaza.setText("Mostaza (+0,50 €)");
        menuItem_SalsasMostaza.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuSalsas.add(menuItem_SalsasMostaza);
        menuSalsas.add(spinnerMostaza);

        menuItem_SalsasThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_SalsasThai.setText("Thai (+0,50 €)");
        menuItem_SalsasThai.setMargin(new java.awt.Insets(4, 2, 4, 2));
        menuSalsas.add(menuItem_SalsasThai);
        menuSalsas.add(spinnerThai);

        menu02.add(menuSalsas);

        menuBar_BurgerApp.add(menu02);

        menu03.setText("Entrega");
        menu03.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        btnGroup_Entrega.add(menuItem_Domicilio);
        menuItem_Domicilio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_Domicilio.setSelected(true);
        menuItem_Domicilio.setText("Reparto a domicilio");
        menuItem_Domicilio.setMargin(new java.awt.Insets(6, 2, 6, 2));
        menu03.add(menuItem_Domicilio);
        menu03.add(jSeparator4);

        btnGroup_Entrega.add(menuItem_Local);
        menuItem_Local.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuItem_Local.setText("Recogida en el local (-20%)");
        menuItem_Local.setMargin(new java.awt.Insets(6, 2, 6, 2));
        menu03.add(menuItem_Local);

        menuBar_BurgerApp.add(menu03);

        setJMenuBar(menuBar_BurgerApp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_HamburguesaPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_HamburguesaPolloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_HamburguesaPolloActionPerformed

    private void menuItem_BebidaLimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_BebidaLimonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_BebidaLimonActionPerformed

    private void menuItem_SalsasBarbacoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_SalsasBarbacoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_SalsasBarbacoaActionPerformed

    private void menuExtra_HamburguesaDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExtra_HamburguesaDobleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExtra_HamburguesaDobleActionPerformed

    private void btn_ConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmarPedidoActionPerformed
        double precio=8;
        int contadorSalsas=0;
        boolean repartoDomicilio=true;
        
        /*El HashMap lo utilizo para ir introduciendo como valor en cda clave las opciones elegidas 
        por el usuario y luego mostrarlas en el JTextArea.*/
        Map<String, String> mapBurgerApp = new HashMap<String, String>()
        {{
             put("Carne","");
             put("Pan","");
             put("Patatas","");
             put("Bebida","");
             put("Extras","");
             put("Salsas","");
             put("Entrega","");
        }};
        
        
        /* IF's anidados para opción de CARNE */
        if(menuItem_HamburguesaPollo.isSelected()){
            mapBurgerApp.put("Carne", "Pollo");
        }else{
            if(menuItem_HamburguesaCerdo.isSelected()){
                mapBurgerApp.put("Carne", "Cerdo");
            }else{
                if(menuItem_HamburguesaTernera.isSelected()){
                    mapBurgerApp.put("Carne", "Ternera");
                    precio+=1;
                }else{
                   mapBurgerApp.put("Carne", "Vegana");
                   precio+=1;
                }          
            }
        }
        
        
        /* IF's anidados para opción de PAN */
        if(menuItem_PanNormal.isSelected()){
            mapBurgerApp.put("Pan", "Normal");
        }else{
            if(menuItem_PanIntegral.isSelected()){
                mapBurgerApp.put("Pan", "Integral");
            }else{
                mapBurgerApp.put("Pan", "Centeno");
            }
        }
        
        
        /* IF's anidados para opción de PATATAS */
        if(menuItem_PatatasFritas.isSelected()){
            mapBurgerApp.put("Patatas", "Fritas");
        }else{
            if(menuItem_PatatasGajo.isSelected()){
                mapBurgerApp.put("Patatas", "Gajo");
            }else{
                mapBurgerApp.put("Patatas", "Caseras");
                precio+=1;
            }
        }
        
        
        /* IF's anidados para opción de BEBIDAS */
        if(menuItem_BebidaCola.isSelected()){
            mapBurgerApp.put("Bebida", "Coca Cola");
        }else{
            if(menuItem_BebidaNaranja.isSelected()){
                mapBurgerApp.put("Bebida", "Fanta de Naranja");
            }else{
                if(menuItem_BebidaLimon.isSelected()){
                    mapBurgerApp.put("Bebida", "Fanta de Limón");
                }else{
                    if(menuItem_BebidaAgua.isSelected()){
                        mapBurgerApp.put("Bebida", "Agua");
                    }else{
                        mapBurgerApp.put("Bebida", "Cerveza");
                    } 
                }
            }
        }
        
        
        /* IF's anidados para opción de SALSAS */
        if((int)spinnerKetchup.getValue()>0){
            contadorSalsas+=(int)spinnerKetchup.getValue();
            mapBurgerApp.put("Salsas", "Ketchup(x"+spinnerKetchup.getValue()+")");
        }
        if((int)spinnerBarbacoa.getValue()>0){
            contadorSalsas+=(int)spinnerBarbacoa.getValue();
            mapBurgerApp.put("Salsas", mapBurgerApp.get("Salsas")+", Barbacoa(x"+spinnerBarbacoa.getValue()+")");
        }
        if((int)spinnerMostaza.getValue()>0){
            contadorSalsas+=(int)spinnerMostaza.getValue();
            mapBurgerApp.put("Salsas", mapBurgerApp.get("Salsas")+", Mostaza(x"+spinnerMostaza.getValue()+")");
        }
        if((int)spinnerThai.getValue()>0){
            contadorSalsas+=(int)spinnerThai.getValue();
            mapBurgerApp.put("Salsas", mapBurgerApp.get("Salsas")+", Thai(x"+spinnerThai.getValue()+")");
        }
        
        /* IF's anidados para los EXTRAS */
        if(contadorSalsas>0){
            if(menuExtra_HamburguesaDoble.isSelected() && menuExtra_Queso.isSelected() && menuExtra_Patatas.isSelected()){
                mapBurgerApp.put("Extras","- Hamburguesa doble (+2 €)\n- Extra de queso (+0,50 €)\n- Extra de patatas (+1 €)\n- Salsas (+0,50 €/salsa): "+contadorSalsas);
                precio+=2+0.5+1+(contadorSalsas*0.5);
            }else{
               if(menuExtra_HamburguesaDoble.isSelected() && menuExtra_Queso.isSelected()){
                    mapBurgerApp.put("Extras","- Hamburguesa doble (+2 €)\n- Extra de queso (+0,50 €)\n- Salsas (+0,50 €/salsa): "+contadorSalsas);
                    precio+=2+0.5+(contadorSalsas*0.5);
                }else{
                    if(menuExtra_HamburguesaDoble.isSelected() && menuExtra_Patatas.isSelected()){
                        mapBurgerApp.put("Extras","- Hamburguesa doble (+2 €)\n- Extra de patatas (+1 €)\n- Salsas (+0,50 €/salsa): "+contadorSalsas);
                        precio+=2+1+(contadorSalsas*0.5);
                    }else{
                        if(menuExtra_Queso.isSelected() && menuExtra_Patatas.isSelected()){
                            mapBurgerApp.put("Extras","- Extra de queso (+0,50 €)\n- Extra de patatas (+1 €)\n- Salsas (+0,50 €/salsa): "+contadorSalsas);
                            precio+=0.5+1+(contadorSalsas*0.5);  
                        }else{
                            if(menuExtra_HamburguesaDoble.isSelected()){
                               mapBurgerApp.put("Extras","- Hamburguesa doble (+2 €)\n- Salsas (+0,50 €/salsa): "+contadorSalsas);
                               precio+=2+(contadorSalsas*0.5);
                            }
                            if(menuExtra_Queso.isSelected()){
                               mapBurgerApp.put("Extras","- Extra de queso (+0,50 €)\n- Salsas (+0,50 €/salsa): "+contadorSalsas);
                               precio+=0.5+(contadorSalsas*0.5);
                            }
                            if(menuExtra_Patatas.isSelected()){
                               mapBurgerApp.put("Extras","- Extra de patatas (+1 €)\n- Salsas (+0,50 €/salsa): "+contadorSalsas);
                               precio+=1+(contadorSalsas*0.5);
                            }
                        }
                    }
                }        
            }
        }else{
            if(menuExtra_HamburguesaDoble.isSelected() && menuExtra_Queso.isSelected() && menuExtra_Patatas.isSelected()){
                mapBurgerApp.put("Extras","- Hamburguesa doble (+2 €)\n- Extra de queso (+0,50 €)\n- Extra de patatas (+1 €)");
                precio+=2+0.5+1;
            }else{
               if(menuExtra_HamburguesaDoble.isSelected() && menuExtra_Queso.isSelected()){
                    mapBurgerApp.put("Extras","- Hamburguesa doble (+2 €)\n- Extra de queso (+0,50 €)");
                    precio+=2+0.5;
                }else{
                    if(menuExtra_HamburguesaDoble.isSelected() && menuExtra_Patatas.isSelected()){
                        mapBurgerApp.put("Extras","- Hamburguesa doble (+2 €)\n- Extra de patatas (+1 €)");
                        precio+=2+1;
                    }else{
                        if(menuExtra_Queso.isSelected() && menuExtra_Patatas.isSelected()){
                            mapBurgerApp.put("Extras","- Extra de queso (+0,50 €)\n- Extra de patatas (+1 €)");
                            precio+=0.5+1;  
                        }else{
                            if(menuExtra_HamburguesaDoble.isSelected()){
                               mapBurgerApp.put("Extras","- Hamburguesa doble (+2 €)");
                               precio+=2;
                            }
                            if(menuExtra_Queso.isSelected()){
                               mapBurgerApp.put("Extras","- Extra de queso (+0,50 €)");
                               precio+=0.5;
                            }
                            if(menuExtra_Patatas.isSelected()){
                               mapBurgerApp.put("Extras","- Extra de patatas (+1 €)");
                               precio+=1;
                            }
                        }
                    }
                }        
            }
        }
        
        
        /* IF para tipo de ENTREGA */
        if(menuItem_Domicilio.isSelected()){
            mapBurgerApp.put("Entrega","Reparto a domicilio");
        }else{
            mapBurgerApp.put("Entrega","Recogida en el local (-20%)");
            repartoDomicilio=false;
        }
        
        /* Aquí se escriben todas las opciones elegidas en el textArea recuperándolas del HashMap */
        textArea_Pedido.setText("Menú (8€):"
                                +"\n- Hamburguesa de "+mapBurgerApp.get("Carne")+" con pan "+mapBurgerApp.get("Pan")
                                +"\n- Patatas: "+mapBurgerApp.get("Patatas")
                                +"\n- Bebida: "+mapBurgerApp.get("Bebida")
                                +"\nExtras:\n"+mapBurgerApp.get("Extras")+" ---> "+mapBurgerApp.get("Salsas")
                                +"\n\n"+mapBurgerApp.get("Entrega")
        
        );
        
        /*Se escriben en los textField correspondientes los precios*/
        textField_Precio.setText(""+precio);
        textField_IVA.setText(""+(precio+(precio*0.21)));
        if(repartoDomicilio==true){
            textField_PrecioFinal.setText(""+(precio+(precio*0.21)));
        }else{
            label_RecogidaLocal.setText("Recogida en Local: 20% de descuento");
            textField_PrecioFinal.setText(""+((precio+(precio*0.21))-((precio+(precio*0.21))*0.2)));
        }

    }//GEN-LAST:event_btn_ConfirmarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurgerMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurgerMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurgerMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurgerMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurgerMenuApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup_Bebida;
    private javax.swing.ButtonGroup btnGroup_CarneHamburguesa;
    private javax.swing.ButtonGroup btnGroup_Entrega;
    private javax.swing.ButtonGroup btnGroup_Pan;
    private javax.swing.ButtonGroup btnGroup_Patatas;
    private javax.swing.JButton btn_ConfirmarPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JLabel label_IVA;
    private javax.swing.JLabel label_Pedido;
    private javax.swing.JLabel label_Precio;
    private javax.swing.JLabel label_PrecioFinal;
    private javax.swing.JLabel label_RecogidaLocal;
    private javax.swing.JMenu menu01;
    private javax.swing.JMenu menu02;
    private javax.swing.JMenu menu03;
    private javax.swing.JMenuBar menuBar_BurgerApp;
    private javax.swing.JMenu menuBebida;
    private javax.swing.JCheckBoxMenuItem menuExtra_HamburguesaDoble;
    private javax.swing.JCheckBoxMenuItem menuExtra_Patatas;
    private javax.swing.JCheckBoxMenuItem menuExtra_Queso;
    private javax.swing.JMenu menuHamburguesa;
    private javax.swing.JCheckBoxMenuItem menuItem_BebidaAgua;
    private javax.swing.JCheckBoxMenuItem menuItem_BebidaCerveza;
    private javax.swing.JCheckBoxMenuItem menuItem_BebidaCola;
    private javax.swing.JCheckBoxMenuItem menuItem_BebidaLimon;
    private javax.swing.JCheckBoxMenuItem menuItem_BebidaNaranja;
    private javax.swing.JCheckBoxMenuItem menuItem_Domicilio;
    private javax.swing.JCheckBoxMenuItem menuItem_HamburguesaCerdo;
    private javax.swing.JCheckBoxMenuItem menuItem_HamburguesaPollo;
    private javax.swing.JCheckBoxMenuItem menuItem_HamburguesaTernera;
    private javax.swing.JCheckBoxMenuItem menuItem_HamburguesaVegana;
    private javax.swing.JCheckBoxMenuItem menuItem_Local;
    private javax.swing.JCheckBoxMenuItem menuItem_PanCenteno;
    private javax.swing.JCheckBoxMenuItem menuItem_PanIntegral;
    private javax.swing.JCheckBoxMenuItem menuItem_PanNormal;
    private javax.swing.JCheckBoxMenuItem menuItem_PatatasCaseras;
    private javax.swing.JCheckBoxMenuItem menuItem_PatatasFritas;
    private javax.swing.JCheckBoxMenuItem menuItem_PatatasGajo;
    private javax.swing.JCheckBoxMenuItem menuItem_SalsasBarbacoa;
    private javax.swing.JCheckBoxMenuItem menuItem_SalsasKetchup;
    private javax.swing.JCheckBoxMenuItem menuItem_SalsasMostaza;
    private javax.swing.JCheckBoxMenuItem menuItem_SalsasThai;
    private javax.swing.JMenu menuPan;
    private javax.swing.JMenu menuPatatas;
    private javax.swing.JMenu menuSalsas;
    private javax.swing.JTextArea textArea_Pedido;
    private javax.swing.JTextField textField_IVA;
    private javax.swing.JTextField textField_Precio;
    private javax.swing.JTextField textField_PrecioFinal;
    // End of variables declaration//GEN-END:variables
}
